### ISSUE TITLE
Alias colour/color

### ISSUE THREAD

**Issue by ntoll** [waveform80/colorzero#5]
Hi,

In British schools teachers will want to use British spelling. Please can you alias things so both spellings work. Thanks!

**Comment by waveform80** [comment]
Sorry, but this is one of the things I rail against whenever it comes up!

### Extended justification

Let's establish first that the human lingua franca in computing is English: specifically, American English. I can't think of a single major library/system that uses any other dialect (examples: [Qt](http://doc.qt.io/qt-5/qml-color.html), [Gdk](https://developer.gnome.org/gtkmm/stable/classGdk_1_1Color.html), [SVG](https://www.w3.org/TR/SVG11/color.html#ColorProperty), [CSS](https://www.w3.org/TR/2018/PR-css-color-3-20180315/#foreground)) or even provides alternate spellings for British/other dialects.

**So what? What's the harm in British aliases?**

The slippery slope. If we provide British spellings ... why not `class Couleur` for French kids or `class Farbe` for German?

**But those aren't *English* dialects**

No, but they're not American English either and that's the point: it's not just a standard language, it's a standard set of spellings because computers are damned picky about that sort of thing.

**But it makes it easier, and that's important for education**

If we're going to make things easier for British kids ... shouldn't we afford the same opportunity to French kids? After all, they've got it harder: they've still got to learn some English to deal with the keywords "if", "for", "while", etc. not to mention all the library routines.

To be fair, I've some sympathy with the notion that a library targeted at education should aim to simplify its interface as much as possible (at this point I'd link to the talk Ben & I gave at PyconUK a while back covering the rationale behind GPIO Zero, but unfortunately it didn't get recorded ... possibly mercifully!). However, to my mind there's two paths to go down here:

1. We stick with American English. Everybody has to learn to spell "Color".
2. We allow regional variation. Everybody gets to use whatever dialect they like, once supported.

From the British user's point of view there's a *minute* amount of pain involved in the first one (learn "Color" instead of "Colour"), and none in the second. From everyone else's point of view there's effectively no difference: they've got to learn English *anyway* to deal with the language (and every other library in that language), so learning "Color" vs their own spelling for a single class in a single library is neither here nor there.

From my point of view, however, there's a huge difference. Option 1 is little effort to maintain, while option 2 leads to me adding `class Цвет` for the Russians, `class Χρώμα` for the Greeks, and `class 颜色` for the Chinese (and I can't even type most of those characters)!

**Now you're just being silly; that's not valid Python**

On the contrary: Python 3 permits Unicode letters in identifiers, so those are perfectly valid Python examples:

```python3
>>> class Color:
...     pass
>>> Цвет = Color
>>> Χρώμα = Color
>>> 颜色 = Color
>>> c = Цвет()
>>> c
<__main__.Color object at 0x7f5b5cd88c88>
>>> d = 颜色()
>>> d
<__main__.Color object at 0x7f5b5aa97860>
```

I can only assume mathematicians will love that this is now valid Python:

```python3
>>> import math
>>> π = math.pi
>>> π
3.141592653589793
>>> ε = 1e-6
>>> a = math.sin(π)
>>> aʹ = math.sin(π+ε)
>>> math.isclose(a, aʹ, abs_tol=ε)
False
```

**But nobody's *really* going to demand/use that?**

Again, on the contrary: I've already had the (exceedingly painful) experience of debugging an SQL stored procedure in Korean (several databases have supported Unicode in identifiers for a while). All the table names, all the column names, all the variables: Korean. Couldn't read it, couldn't type it. Had to copy'n'paste every damned variable name. Frankly, that just made me all the more determined to standardize on a single dialect, and encourage others to do the same.

**But we're not asking for that: we just want *English*!**

And you've got it: American English.

I'll say this as a Brit myself: forget any notion that "we invented the language". After all the etymology of "colour" derives from Old French. Even if it didn't, I wouldn't care because who invented the language or what dialect came first is irrelevant. What matters is that the computing industry at large has standardized on American English, largely as a result of America being the country that took most advantage of the invention of computing (you can argue amongst yourselves as to who *invented* computing, but I'd say it's fairly indisputable that the Americans *commercialized* it). Furthermore, the industry standardizing on American English is *no bad thing*! The alternative of a myriad of dialects, or worse still alphabets, strikes me as an horrifically complex proposition and one I'm in no rush to encourage (despite Python 3's steps toward embracing it).

Finally, the "third option": permit American and British English ... but nothing else, I find to be philosophically indefensible. It's neither adhering to a standard, nor embracing the rich variety of cultures. It's just us Brits demanding special treatment ... again!

----

P.S. I don't mean this to be a personal attack in any way. I understand you'll either have been asked this, or are anticipating being asked it, so I figured I'd post an extended justification to give you something to point people at :)
